version: "3.9"

services:
  db:
    image: "postgres"
    restart: always
    container_name: "chaos-tests-postgres"
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: "chaos-test"
      POSTGRES_USER: "chaos"
      POSTGRES_PASSWORD: "chaos"
