version: "3.8"

services:
  db:
    image: "postgres"
    container_name: "chaos-postgres"
    restart: always
    environment:
      POSTGRES_DB: "chaos"
      POSTGRES_USER: "chaos"
      POSTGRES_PASSWORD: "chaos"
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db:
    driver: local
