'use client'
export { default as AddIcon } from '@mui/icons-material/Add'
export { default as DeleteIcon } from '@mui/icons-material/Delete'
export { default as EditIcon } from '@mui/icons-material/Edit'
export { default as FavoriteIcon } from '@mui/icons-material/Favorite'
export { default as MoreVertIcon } from '@mui/icons-material/MoreVert'
export { default as SearchIcon } from '@mui/icons-material/Search'
export { default as ShareIcon } from '@mui/icons-material/Share'
